
81: chi-square test
80: group by + join (using with)
79: INCOMPLETE (do not understand the problem)
78: max and second max
77: group by + join
76: resampling imbalanced data (oversampling, undersampling, one-class learning, asym-loss function)
75: group by + avg
74: df['farenheit'] = df['celcius'].apply(lambda F: 5*(F-32)/9)
73: single sample t-test
72: two update queries
71: df.apply + datetime
70: inside loop increments counter before printing
69: 



In [4]:
"""
    Problem 81
    fitness: low, medium, medium-high, high
    https://machinelearningmastery.com/chi-squared-test-for-machine-learning/
"""
never_smoked = [113, 113, 110, 159]
former_smokers = [119, 135, 172, 190]
one_to_nine_daily = [77, 91, 86, 65]
at_least_ten_daily = [181, 152, 124, 73]

"""
    Is there a relation between smoking and fitness level ?
"""
import pandas as pd

df = pd.DataFrame({'never_smoked': never_smoked, 
                  'former_smokers': former_smokers, 
                  'one_to_nine_daily': one_to_nine_daily,
                  'at_least_ten_daily': at_least_ten_daily}).T

In [8]:
df.columns = ['low', 'medium', 'med-high', 'high']

In [9]:
df

low  medium  med-high  high
never_smoked        113     113       110   159
former_smokers      119     135       172   190
one_to_nine_daily    77      91        86    65
at_least_ten_daily  181     152       124    73

In [20]:
from scipy.stats import chi2_contingency
from scipy.stats import chi2
print("H0: the distribution of fitness level is independent of smoker status")
print("\n")
# contingency table
table = df
print(table)
print('\n')
stat, p, dof, expected = chi2_contingency(table)
print('Degrees of freedom = {}'.format(dof))
print("The expected values are:")
print(expected)
print("\n")
print("Interpreting the test statistics:")
# interpret test-statistic
prob = 0.95
critical = chi2.ppf(prob, dof)
print('probability=%.3f, critical=%.3f, stat=%.3f' % (prob, critical, stat))
if abs(stat) >= critical:
    print('Dependent (reject H0)')
else:
    print('Independent (fail to reject H0)')
print('\n')    
print("p-value")    
# interpret p-value
alpha = 1.0 - prob
print('significance=%.3f, p=%.3f' % (alpha, p))
if p <= alpha:
    print('Dependent (reject H0)')
else:
    print('Independent (fail to reject H0)')

H0: the distribution of fitness level is independent of smoker status


                    low  medium  med-high  high
never_smoked        113     113       110   159
former_smokers      119     135       172   190
one_to_nine_daily    77      91        86    65
at_least_ten_daily  181     152       124    73


Degrees of freedom = 9
The expected values are:
[[123.75       124.00255102 124.25510204 122.99234694]
 [154.         154.31428571 154.62857143 153.05714286]
 [ 79.75        79.9127551   80.0755102   79.26173469]
 [132.5        132.77040816 133.04081633 131.68877551]]


Interpreting the test statistics:
probability=0.950, critical=16.919, stat=87.273
Dependent (reject H0)


p-value
significance=0.050, p=0.000
Dependent (reject H0)


In [18]:
num_never_smoked = (113 + 113 + 110 + 159) 
num_low_fitness = (113 + 119 + 77 + 181) 
total = (113 + 113 + 110 + 159 + 119 + 135 + 172 + 190 + 77 + 91 + 86 + 65 + 181 + 152 + 124 + 73)

expected_never_smoke_and_low_fitness = num_never_smoked*num_low_fitness/total
expected_never_smoke_and_low_fitness

123.75

In [7]:
"""
    airbnb: channel attribution
    
    interesting link: https://medium.com/data-from-the-trenches/marketing-attribution-e7fa7ae9e919
"""

import pandas as pd
df = pd.read_csv("../Data/channel_attribution/airbnb_test.csv")

In [2]:
df.head()

id date_account_created     gender   age signup_method language  \
0  5uwns89zht           2014-07-01     FEMALE  35.0      facebook       en   
1  jtl0dijy2j           2014-07-01  -unknown-   NaN         basic       en   
2  xx0ulgorjt           2014-07-01  -unknown-   NaN         basic       en   
3  6c6puo6ix0           2014-07-01  -unknown-   NaN         basic       en   
4  czqhjk3yfe           2014-07-01  -unknown-   NaN         basic       en   

  affiliate_channel affiliate_provider signup_app first_device_type  \
0            direct             direct      Moweb            iPhone   
1            direct             direct      Moweb            iPhone   
2            direct             direct        Web   Windows Desktop   
3            direct             direct        Web   Windows Desktop   
4            direct             direct        Web       Mac Desktop   

   first_browser  
0  Mobile Safari  
1  Mobile Safari  
2         Chrome  
3             IE  
4         Safari

In [11]:
df.dtypes

id                       object
date_account_created     object
gender                   object
age                     float64
signup_method            object
language                 object
affiliate_channel        object
affiliate_provider       object
signup_app               object
first_device_type        object
first_browser            object
dtype: object

In [29]:
len(df['date_account_created'].unique())

92

In [30]:
df['affiliate_channel'].value_counts()

direct           43844
sem-brand        10394
seo               5699
sem-non-brand     1231
other              586
remarketing        172
content            170
Name: affiliate_channel, dtype: int64

In [34]:
df['affiliate_provider'].unique()

array(['direct', 'google', 'bing', 'facebook', 'other', 'craigslist',
       'padmapper', 'email-marketing', 'yahoo', 'baidu', 'naver', 'gsp',
       'facebook-open-graph', 'meetup', 'vast', 'daum', 'yandex'],
      dtype=object)

In [35]:
df['signup_app'].unique()

array(['Moweb', 'Web', 'iOS', 'Android'], dtype=object)

In [36]:
df['first_browser'].unique()

array(['Mobile Safari', 'Chrome', 'IE', 'Safari', '-unknown-', 'Firefox',
       'Chrome Mobile', 'Android Browser', 'IE Mobile',
       'BlackBerry Browser', 'Opera', 'Silk', 'Mobile Firefox',
       'AOL Explorer', 'SeaMonkey', 'Opera Mobile', 'wOSBrowser',
       'Chromium', 'Apple Mail', 'Maxthon', 'IBrowse', 'Sogou Explorer',
       'Iron', 'Yandex.Browser', 'SiteKiosk', 'Pale Moon',
       'Nintendo Browser', 'Opera Mini', 'CometBird', 'IceWeasel',
       'UC Browser'], dtype=object)

In [26]:
def fraction_of_nans(df):
    for column in df.columns.tolist():
        print("{}: {}".format(column, 1-df[column].count()/len(df)))
        
fraction_of_nans(df)        

id: 0.0
date_account_created: 0.0
gender: 0.0
age: 0.4650219015717598
signup_method: 0.0
language: 0.0
affiliate_channel: 0.0
affiliate_provider: 0.0
signup_app: 0.0
first_device_type: 0.0
first_browser: 0.0


In [31]:
import numpy as np
df['age'] = df['age'].astype(np.float32)

In [33]:
"""
    test if all ids are unique
"""
df['id'].nunique() == len(df)

True

# Resampling
Can you explain what resampling is? Can you name 2 seperate resampling methods and explain the pros and cons?

Resampling is remedy used when data is imbalanced.
Let us say in binary classification problem (e.g. fraud detection), the number of positive samples (cases of fraud) available are much smaller compared to the number of negative samples.
Why is it a problem ? Because many ML algorithms are unable to learn well from imbalanced datasets.
https://stats.stackexchange.com/questions/247871/what-is-the-root-cause-of-the-class-imbalance-problem
The stack-overflow answers seem to suggest that "loss-functions that penalize both classes uniformly" seem to be the root cause.

How to solve the class-imbalance problem ?
Apart from using balanced loss function, resampling methods seem to be used in practice.
https://stats.stackexchange.com/questions/131255/class-imbalance-in-supervised-machine-learning/131259#131259

There are 4 types: 
1. Oversampling smaller class
2. Undersampling larger class
3. One class learning (denoise the data)
4. Asymmetric cost function

Example of one-class svm: https://scikit-learn.org/stable/auto_examples/svm/plot_oneclass.html

# One-sample t-test
https://plot.ly/python/t-test/


https://python-forum.io/Thread-Plot-a-stacked-bar-graph-using-plotly-offline-mode

In [1]:
"""
    selenimum toxicity of water
    t-test
"""
import pandas as pd

toxs = [0.051,
0.0505,
0.049,
0.0516,
0.052,
0.0508,
0.0506]

danger = 0.05 # mg/L
df = pd.DataFrame({'day': list(range(1, 8)), 'toxicity': toxs})

In [3]:
df

day  toxicity
0    1    0.0510
1    2    0.0505
2    3    0.0490
3    4    0.0516
4    5    0.0520
5    6    0.0508
6    7    0.0506

In [2]:
from scipy.stats import ttest_1samp
from plotly.tools import FigureFactory as FF
import plotly.plotly as py

true_mu = 0.05

onesample_results = ttest_1samp(df['toxicity'], true_mu)
onesample_results

Ttest_1sampResult(statistic=2.173499949434694, pvalue=0.07271011867964246)

In [4]:
from plotly.offline import init_notebook_mode, plot
init_notebook_mode(connected=True)
 
matrix_onesample = [
    ['', 'Test Statistic', 'p-value'],
    ['Sample Data', onesample_results[0], onesample_results[1]]
]

onesample_table = FF.create_table(matrix_onesample, index=True)
plot(onesample_table, filename='onesample-table')
# py.iplot(onesample_table, filename='onesample-table')

/home/raghav/anaconda3/lib/python3.6/site-packages/plotly/tools.py:1545: UserWarning:

plotly.tools.FigureFactory.create_table is deprecated. Use plotly.figure_factory.create_table



'file:///home/raghav/Practice/MLPractice/Notebooks/temp-plot.html'

# Two sample t-test
https://towardsdatascience.com/inferential-statistics-series-t-test-using-numpy-2718f8f9bf2f

In [41]:
## Import the packages
import numpy as np
from scipy import stats

## Define 2 random distributions
#Sample Size
N = 10
#Gaussian distributed data with mean = 2 and var = 1
a = np.random.randn(N) + 2
#Gaussian distributed data with with mean = 0 and var = 1
b = np.random.randn(N)

## Calculate the Standard Deviation
#Calculate the variance to get the standard deviation

#For unbiased max likelihood estimate we have to divide the var by N-1, and therefore the parameter ddof = 1
var_a = a.var(ddof=1)
var_b = b.var(ddof=1)

#std deviation
s = np.sqrt((var_a + var_b)/2)
s

## Calculate the t-statistics
t = (a.mean() - b.mean())/(s*np.sqrt(2/N))

## Compare with the critical t-value
#Degrees of freedom
df = 2*N - 2

#p-value after comparison with the t 
p = 1 - stats.t.cdf(t,df=df)

print("t = " + str(t))
print("p = " + str(2*p))
#Note that we multiply the p value by 2 because its a twp tail t-test
### You can see that after comparing the t statistic with the critical t value (computed internally) we get a good p value of 0.0005 and thus we reject the null hypothesis and thus it proves that the mean of the two distributions are different and statistically significant.


## Cross Checking with the internal scipy function
t2, p2 = stats.ttest_ind(a,b)
print("t = " + str(t2))
print("p = " + str(2*p2))

t = 5.963825577165308
p = 1.2137653838006912e-05
t = 5.963825577165308
p = 2.4275307676043548e-05


"""
    Q: What is bias-variance trade-off ? 
    Suppose we want to learn a function y = f(x) + eps.
    We fit a function g to the observations (y_1, x_1), ..., (y_n, x_n).
    Then g corresponds to our learned ML model.
    
    The generalization (mean square) error of an ML model can be typically decomposed into 3 parts as follows:
    
                       generalization error = bias^2 + variance + noise
                       
     where bias^2 is the error attributed to the inherent limitation of model to approximate f,
           variance is the error part attributed to the variability in the predictions of the model,
           and noise is the irreducible error attributed to the inherent noise in the dataset
           
     More precisely, for a fixed test example x:
           generalization error = E[(y-g(x))^2]
           bias(g) = E[g(x)-f(x)]
           variance(g) = E[g(x)^2] - E[g(x)]^2
           noise = variance(y) = variance(eps)
           
     Here the expectations are taken over a random choise of n-sample dataset D_n   
     
     Ideally, in order to achieve a low generalization error, 
     we want both bias and variance to be as close to zero as possible.
     
     However typically there is a trade-off between the two errors:
           - models with very low bias tend to have high variance
           - models with very low variance tend to have high bias
           
     This is partly because we are trying to infer an approximation of f by looking at its values
     only on a limited set of points x_1, ..., x_n.
     
     If we choose g that approximates f too closely on these n points then g might capture some
     patterns in this particular dataset that do not generalize on other points, leading to high variance.
     
     If we want to keep the variance low then we might not be able to approximate f too closely.
     
     Typically:
         - high model complexity => high variance => overfitting
         - low model complexity => high bias => underfitting
         
     Q: What are the situations in practice where one might want to use biased estimators ? 
         - when model is overfitting: 
           regularization achieves decrease in variance by small increase in bias
           so that overall the generalization error decreases
           https://stats.stackexchange.com/questions/207760/when-is-a-biased-estimator-preferable-to-unbiased-one
"""

"""
"""

https://stackoverflow.com/questions/22898824/filtering-pandas-dataframes-on-dates
"""
    table: 
    date|timestamp|sender_id|receiver_id
    
    Goal: obtain fraction of messages that receive a response within 5 min on March 1, 2018
    
    df[df.date == datetime.date(2018, 03, 01)]
    
    
"""
